version: '3.9'

services:
  php:
    container_name: PHP-Apache
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always 
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:80"
    networks:
      - lamp-docker
    stdin_open: true
    tty: true    
    volumes:
      - ./PHP-MYSQL-con-Docker:/var/www/html

  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    networks:
      - lamp-docker
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    container_name: Mysql-Apache
    
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "9090:9090"

networks:
  lamp-docker:
      
    